<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
            <div class="card-body">

                <div class="d-flex justify-content-center">
                    <a href="/">
                        <img src="/img/twitter_logo.png" />
                    </a>
                </div>

                <div class="row">
                    <div class="col">
                        <h2>Crie sua conta</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col">

                        <form action="/registrar" method="post">
                            <div class="form-group">
                                <input type="text" value="<?php echo $this->view->usuario['nome'] ; ?>" class="form-control" placeholder="Nome" name="nome" required>
                            </div>

                            <div class="form-group">
                                <input type="text" value="<?php echo $this->view->usuario['email'] ; ?>" class="form-control" placeholder="E-mail" name="email" required>
                            </div>

                            <div class="form-group">
                                <input type="password" value="<?php echo $this->view->usuario['senha'] ; ?>" class="form-control" placeholder="Senha" name="senha" required>
                            </div>

                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Confirme sua Senha" name="reSenha" required>
                            </div>



                            <div class="mt-4 mb-4">
                                <small class="form-text">
                                    Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                                </small>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>

                            <?php

                                if ($this->view->erro[0] == true) {

                                    if ($this->view->erro['erro'] == 0) { ?>

                                        <small class="form-text text-danger text-center pt-3">*Dados Invalidos ou Já Existentes, confira os campos acima!</small>

                                    <?php } else if ($this->view->erro['erro'] == 1) { ?>

                                        <small class="form-text text-danger text-center pt-3">*As senhas não condizem, preencha corretamente !</small>
                                <?php }
                                }

                            ?>

                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>