<?php require '../app/View/app/tweetNavBar.phtml';?>

<?php 

	var_dump($_POST);
	if(isset($_POST['tweetId'])){
		echo $_POST['tweetId'];
	}


?>

<div class="container mt-5">

	<div class="row pt-2">
		
		<?php require '../app/View/app/tweetMenu.phtml';?>

		<div class="col-md-6">

			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/tweet" method="POST">
						<textarea class="form-control" id="exampleFormControlTextarea1" name="tweet" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as  $tweet){?>
				<div class="row tweet">
					<div class="col">
						<p>
							<strong><?php echo $tweet['nome'] ;?></strong> 
							<small><span class="text text-muted">- <?php echo $tweet['data'] ;?></span></small>
						</p>

						<p><?php echo $tweet['tweet'] ;?></p>

						<br />
						<?php if($tweet['id_usuario'] == $_SESSION['id']){ ?>
							<form method="POST" action="/deletarTweet">
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
									<input type="text" name="tweetId" value="<?php echo $tweet['id'] ?>" hidden>
								</div>
							</form>
						<?php }else{?>
							<form>
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger"><i class="fa-solid fa-heart"></i></button>
									<input type="text" name="tweetId" value="<?php echo $tweet['id'] ?>" hidden>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>

		</div>

		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>

</div>

<script>
	document.querySelector('#menuItem').classList.add('focus')
</script>